# We build upon the default config provided by https://github.com/arturbosch/detekt/blob/master/detekt-cli/src/main/resources/default-detekt-config.yml
build:
  maxIssues: 0

processors:
  active: true

complexity:
  ComplexCondition:
    active: false
  TooManyFunctions:
    active: false

console-reports:
  active: true

style:
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 100
