trigger:
- master

jobs:
- job: iOS_dist
  timeoutInMinutes: 360
  pool:
    vmImage: 'macos-latest'
  steps:
    - checkout: self
      submodules: true
    - script: ./envoy/ci/mac_ci_setup.sh
      displayName: 'Install dependencies'
    - script: bazel build //:ios_dist --config=ios
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'Envoy.framework'
        targetPath: 'dist/Envoy.framework'
- job: iOS_objc
  dependsOn: iOS_dist
  timeoutInMinutes: 360
  pool:
    vmImage: 'macos-latest'
  steps:
    - checkout: self
      submodules: true
    - script: ./envoy/ci/mac_ci_setup.sh
      displayName: 'Install dependencies'
    - script: mkdir -p dist/Envoy.framework
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: Envoy.framework
        targetPath: ./dist/Envoy.framework
    - script: bazel build //examples/objective-c/hello_world:app --config=ios
- job: iOS_swift
  dependsOn: iOS_dist
  timeoutInMinutes: 360
  pool:
    vmImage: 'macos-latest'
  steps:
    - checkout: self
      submodules: true
    - script: ./envoy/ci/mac_ci_setup.sh
      displayName: 'Install dependencies'
    - script: mkdir -p dist/Envoy.framework
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: Envoy.framework
        targetPath: ./dist/Envoy.framework
    - script: bazel build //examples/swift/hello_world:app --config=ios