resources:
  containers:
  - container: envoy-container
    image: envoyproxy/envoy-build:cfc514546bc0284536893cca5fa43d7128edcd35
  - container: swiftlint-container
    image: norionomura/swiftlint:0.33.0_swift-5.0
  - container: jdk8
    image: openjdk:8-jdk

trigger:
- master

stages:
  - stage: performance
    dependsOn: [] # this removes the implicit dependency on previous stage and causes this to run in parallel.
    jobs:
      - job: size_current
        timeoutInMinutes: 60
        pool:
          vmImage: 'macos-10.14'
        steps:
          - checkout: self
            submodules: true
          - script: ./ci/mac_ci_setup.sh
            displayName: 'Install dependencies'
          - script: CC=clang  CXX=clang++ bazel build //test/performance:test_binary_size --config=sizeopt --copt=-ggdb3
            displayName: 'Build test binary'
          - script: |
              strip -s -o bazel-bin/test/performance/test_binary_size.stripped bazel-bin/test/performance/test_binary_size
              zip -9 current.zip bazel-bin/test/performance/test_binary_size.stripped
            displayName: 'Strip and Zip binary'
          - task: PublishPipelineArtifact@0
            displayName: 'Publish current test binary'
            inputs:
              artifactName: 'current.zip'
              targetPath: 'current.zip'
      - job: size_master
        timeoutInMinutes: 60
        pool:
          vmImage: 'macos-10.14'
        steps:
          - checkout: self
            submodules: true
          - script: ./ci/mac_ci_setup.sh
            displayName: 'Install dependencies'
          - script: CC=clang  CXX=clang++ bazel build //test/performance:test_binary_size --config=sizeopt --copt=-ggdb3
            displayName: 'Build test binary'
          - script: |
              strip -s -o bazel-bin/test/performance/test_binary_size.stripped bazel-bin/test/performance/test_binary_size
              zip -9 master.zip bazel-bin/test/performance/test_binary_size.stripped
            displayName: 'Strip and Zip binary'
          - task: PublishPipelineArtifact@0
            displayName: 'Publish master test binary'
            inputs:
              artifactName: 'master.zip'
              targetPath: 'master.zip'
      - job: size_compare
        dependsOn:
          - size_current
          - size_master
        timeoutInMinutes: 60
        pool:
          vmImage: 'Ubuntu 16.04'
        steps:
          - task: DownloadPipelineArtifact@0
            displayName: 'Download current test binary'
            inputs:
              artifactName: 'current.zip'
              targetPath: dist
          - task: DownloadPipelineArtifact@0
            displayName: 'Download master test binary'
            inputs:
              artifactName: 'master.zip'
              targetPath: dist
          - script: ./ci/test_binary_size.sh dist/master.zip dist/current.zip
