name: envoy-mobile
options:
  createIntermediateGroups: true
  defaultConfig: Debug
  groupSortPosition: none
settings:
  CODE_SIGNING_ALLOWED: false
  DONT_RUN_SWIFT_STDLIB_TOOL: true
  CC: $(SRCROOT)/tools/cc-stub.sh
  LD: /usr/bin/true
  LIBTOOL: /usr/bin/true
  SWIFT_EXEC: $(SRCROOT)/tools/swiftc_stub.py
  SWIFT_OBJC_INTERFACE_HEADER_NAME: ""
  SWIFT_VERSION: 5
targets:
  envoy-mobile:
    type: framework.static
    platform: iOS
    settings:
      PRODUCT_MODULE_NAME: Envoy
      PRODUCT_NAME: Envoy.framework
      BAZEL_PACKAGE: library
      USER_HEADER_SEARCH_PATHS:
        - $(SRCROOT)
        - $(SRCROOT)/envoy/source
        - $(SRCROOT)/envoy/include
        - $(SRCROOT)/bazel-envoy-mobile/external/com_google_absl
    preBuildScripts:
      - name: Build with bazel
        script: PATH=${PATH} "$SRCROOT"/tools/xcode-build.sh
    sources:
      - path: library/common
        headerVisibility: project
      - path: library/swift/src
        headerVisibility: project
      - path: library/objective-c
        headerVisibility: project
      - path: envoy/source
        headerVisibility: project
        excludes:
          - "**/*.md"
          - "**/*.py"
          - "**/xDS_code_diagram.png"
      - path: envoy/include
        headerVisibility: project
schemes:
  envoy-mobile:
    build:
      parallelizeBuild: false
      buildImplicitDependencies: false
      targets:
        envoy-mobile: [run]
