version: 2.1

executors:
  ubuntu-build:
    description: "A regular build executor based on ubuntu image"
    docker:
      - image: envoyproxy/envoy-build:cfc514546bc0284536893cca5fa43d7128edcd35
    # TODO(mattklein123): Get xlarge class enabled
    resource_class: medium
    working_directory: /source

jobs:
  docs:
    executor: ubuntu-build
    steps:
      - checkout
      - run: git submodule update --init
      - run: docs/build.sh
      - add_ssh_keys:
          fingerprints:
            - "a2:f7:59:f0:01:8b:91:31:ab:0c:3f:9f:25:4c:1e:e5"
      - run: docs/publish.sh
      - store_artifacts:
          path: generated/docs
  format:
    executor: ubuntu-build
    # TODO(mattklein123): resource_class: small
    steps:
      - checkout
      - run: git submodule update --init
      - run: tools/check_format.sh
  swiftlint:
    docker:
      - image: norionomura/swiftlint:0.33.0_swift-5.0
    steps:
      - checkout
      - run: swiftlint lint
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml

workflows:
  version: 2
  all:
    jobs:
      - docs:
          filters:
            tags:
              only: /^v.*/
      - format
      - swiftlint
