version: 2.1

executors:
  ubuntu-build:
    description: "A regular build executor based on ubuntu image"
    docker:
      - image: envoyproxy/envoy-build:cfc514546bc0284536893cca5fa43d7128edcd35
    # TODO(mattklein123): Get xlarge class enabled
    resource_class: medium
    working_directory: /source
  android:
    description: "A build executor for envoy that has Android SDK and NDK"
    docker:
      - image: junr03/envoy-android:b2f72b270233b582595149be55795e222d79d555
    resource_class: medium
    working_directory: /source

jobs:
  docs:
    executor: ubuntu-build
    steps:
      - checkout
      - run: git submodule update --init
      - run: docs/build.sh
      - add_ssh_keys:
          fingerprints:
            - "a2:f7:59:f0:01:8b:91:31:ab:0c:3f:9f:25:4c:1e:e5"
      - run: docs/publish.sh
      - store_artifacts:
          path: generated/docs
  format:
    executor: ubuntu-build
    # TODO(mattklein123): resource_class: small
    steps:
      - checkout
      - run: git submodule update --init
      - run: tools/check_format.sh
  ios_dist:
    macos:
      xcode: "10.2.1"
    steps:
      - checkout
      - run: git submodule update --init
      - run: ./envoy/ci/mac_ci_setup.sh
      - run: bazel build //:ios_dist --config=ios
      - persist_to_workspace:
          root: dist
          paths:
            - Envoy.framework
  android_dist:
    executor: android
    steps:
      - checkout
      - run: git submodule update --init
      - run: export PATH=/usr/lib/llvm-8/bin:$PATH
      - run: export CC=clang
      - run: export CXX=clang++
      - run: export ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-8/bin/llvm-symbolizer
      - run: bazel build @envoy//source/exe:envoy_main_common_lib
      - persist_to_workspace:
          root: dist
          paths:
            - envoy.aar
  objc_app:
    macos:
      xcode: "10.2.1"
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run: bazel build //examples/objective-c/hello_world:app --config=ios
  swift_app:
    macos:
      xcode: "10.2.1"
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run: bazel build //examples/swift/hello_world:app --config=ios
  java_app:
    executor: android
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run: bazel build //examples/java/hello_world:hello_envoy --fat_apk_cpu=x86

workflows:
  version: 2
  all:
    jobs:
      - docs:
          filters:
            tags:
              only: /^v.*/
      - format
      - ios_dist
      - android_dist
      - objc_app:
          requires:
            - ios_dist
      - swift_app:
          requires:
            - ios_dist
      - java_app:
          requires:
            - android_dist
