licenses(["notice"])  # Apache 2

platform(
    name = "macos",
    constraint_values = [
        "@platforms//cpu:x86_64",
        "@platforms//os:macos",
    ],
    exec_properties = {
        "Pool": "xcode_14",
        "cache-silo-key": "12345",
    },
)
