static_resources:
  listeners:
    - address:
        socket_address: {address: 0.0.0.0, port_value: 9001, protocol: TCP}
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                stat_prefix: client
                route_config:
                  virtual_hosts:
                    - name: all
                      domains: ["*"]
                      routes:
                        - match: {prefix: "/"}
                          route: {cluster: hello_world_api}
                http_filters:
                  - name: envoy.router
  clusters:
    - name: hello_world_api
      connect_timeout: 30s
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: hello_world_api
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address: {address: s3.amazonaws.com, port_value: 443}
      tls_context:
        sni: s3.amazonaws.com
      type: LOGICAL_DNS
