static_resources:
  listeners:
  - address:
      socket_address: {address: 0.0.0.0, port_value: 9001, protocol: TCP}
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: client
          route_config:
            virtual_hosts:
            - name: all
              domains: ["*"]
              routes:
              - match: {prefix: "/"}
                route: {cluster: egress_cluster}
          http_filters:
          - name: envoy.router
  clusters:
  - name: egress_cluster
    connect_timeout: 30s
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: egress_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address: {address: api.lyft.com, port_value: 443}
    tls_context:
      sni: api.lyft.com
    type: LOGICAL_DNS
