load("@envoy_mobile//bazel:kotlin_test.bzl", "envoy_mobile_kt_test")

licenses(["notice"])  # Apache 2

envoy_mobile_kt_test(
    name = "element_test",
    srcs = [
        "ElementTest.kt",
    ],
    deps = [
        "//library/kotlin/io/envoyproxy/envoymobile:envoy_interfaces_lib",
    ],
)

envoy_mobile_kt_test(
    name = "counter_impl_test",
    srcs = [
        "CounterImplTest.kt",
    ],
    deps = [
        "//library/kotlin/io/envoyproxy/envoymobile:envoy_interfaces_lib",
    ],
)

envoy_mobile_kt_test(
    name = "distribution_impl_test",
    srcs = [
        "DistributionImplTest.kt",
    ],
    deps = [
        "//library/kotlin/io/envoyproxy/envoymobile:envoy_interfaces_lib",
    ],
)

envoy_mobile_kt_test(
    name = "gauge_impl_test",
    srcs = [
        "GaugeImplTest.kt",
    ],
    deps = [
        "//library/kotlin/io/envoyproxy/envoymobile:envoy_interfaces_lib",
    ],
)

envoy_mobile_kt_test(
    name = "timer_impl_test",
    srcs = [
        "TimerImplTest.kt",
    ],
    deps = [
        "//library/kotlin/io/envoyproxy/envoymobile:envoy_interfaces_lib",
    ],
)
