name: android

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  macjava:
    name: mac_java_helloworld
    runs-on: macOS-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - run: ls -lh dist/
      - name: start simulator
        run: ./ci/mac_start_emulator.sh
      - run: |
          export ADB_INSTALL_DEFAULT_INCREMENTAL=false
          bazel mobile-install --fat_apk_cpu=x86 --start_app //examples/java/hello_world:hello_envoy
        name: 'Start java app'
      - run: 'adb logcat -e "successful response" -m 1'
        name: 'Check liveliness'
  mackotlin:
    name: mac_kotlin_helloworld
    runs-on: macOS-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - run: ls -lh dist/
      - name: start simulator
        run: ./ci/mac_start_emulator.sh
      - run: ./bzldev mobile-install --fat_apk_cpu=x86 --start_app //examples/kotlin/hello_world:hello_envoy_kt
        name: 'Start kotlin app'
      - run: 'adb logcat -e "successful response" -m 1'
        name: 'Check liveliness'
