name: android_tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  kotlintestsosx:
    name: kotlin_tests_osx
    runs-on: macOS-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - run: |
          # /test/kotlin/integration is excluded since it is run on a separate job
          bazelisk query //test/kotlin/... except //test/kotlin/integration/... | xargs bazelisk test --test_output=all
        name: 'Run Kotlin library tests'
  javatestsosx:
    name: java_tests_osx
    runs-on: macOS-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - run: |
          # /test/kotlin/integration is excluded since it is run on a separate job
          bazelisk query //test/java/... except //test/java/integration/... | xargs bazelisk test --test_output=all
        name: 'Run Java library tests'
