name: android

on: [push]

jobs:
  androiddistlinux:
    name: android_linux_dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/linux_ci_setup.sh
      - name: 'Build envoy.aar distributable'
        run: |
          export PATH=/usr/lib/llvm-8/bin:$PATH
          export CC=clang
          export CXX=clang++
          export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk-bundle
          ./bazelw build --fat_apk_cpu=x86 //:android_dist
      - name: 'Build Java app'
        run: |
          export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk-bundle
          ./bazelw build --fat_apk_cpu=x86 //examples/java/hello_world:hello_envoy
      - name: 'Build kotlin app'
        run: |
          export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk-bundle
          ./bazelw build --fat_apk_cpu=x86 //examples/kotlin/hello_world:hello_envoy_kt
  kotlintests:
    name: kotlin_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/linux_ci_setup.sh
      - run: ./bazelw test --test_output=all --build_tests_only //library/kotlin/test/...
        name: 'Run Kotlin library tests'
  macandroid:
    name: android_mac_test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - name: 'Build envoy.aar distributable'
        run: ./bazelw build --fat_apk_cpu=x86 //:android_dist
      - name: start simulator
        run: ./ci/start_simulator.sh
      - run: ./bazelw mobile-install --fat_apk_cpu=x86 --start_app //examples/java/hello_world:hello_envoy
        name: 'Start java app'
      - run: 'adb logcat -e "successful response!" -m 1'
        name: 'Check liveliness'
