name: android_build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  androidbuild:
    name: android_build
    runs-on: macos-11
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/cache@v2
        id: check-cache
        with:
          key: aar-${{ github.sha }}
          path: dist/envoy.aar
        name: 'Check cache'
      - run: echo "Found envoy.aar from previous run!"
        if: steps.check-cache.outputs.cache-hit == 'true'
        name: 'Build cache hit'
      - uses: actions/setup-java@v1
        if: steps.check-cache.outputs.cache-hit != 'true'
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - name: 'Install dependencies'
        if: steps.check-cache.outputs.cache-hit != 'true'
        run: ./ci/mac_ci_setup.sh
      - name: 'Build envoy.aar distributable'
        if: steps.check-cache.outputs.cache-hit != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bazelisk build \
            --config=remote-ci-macos \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            --fat_apk_cpu=x86 \
            //:android_dist_ci \
            --config=remote-ci-debug
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
