name: android_tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  kotlintestsmac:
    # revert to //test/kotlin/... once fixed
    # https://github.com/envoyproxy/envoy-mobile/issues/1932
    name: kotlin_tests_mac
    runs-on: macos-12
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Run Kotlin library tests'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bazelw test \
            --test_output=all \
            --build_tests_only \
            --config=remote-ci-linux \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //test/kotlin/io/...
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
