name: android_tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  kotlintestsmac:
    # revert to //test/kotlin/... once fixed
    # https://github.com/envoyproxy/envoy-mobile/issues/1932
    name: kotlin_tests_mac
    runs-on: macos-11
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - id: check_context
        name: 'Check whether to run'
        run: |
          if git rev-parse --abbrev-ref HEAD | grep -q ^main$ || git diff --name-only origin/main | grep -qe common/ -e java/ -e kotlin/ -e bazel/ -e ^\.bazelrc$ -e ^envoy$ -e ^WORKSPACE$ -e ^.github/workflows/android_tests.yml$ ; then
            echo "Tests will run."
            echo "::set-output name=run_tests::true"
          else
            echo "Skipping tests."
            echo "::set-output name=run_tests::false"
          fi
      - name: 'Java setup'
        if: steps.check_context.outputs.run_tests == 'true'
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - name: 'Check Java'
        run: |
          java -version
          whereis java
      - name: 'Install dependencies'
        if: steps.check_context.outputs.run_tests == 'true'
        run: ./ci/mac_ci_setup.sh
      - name: 'Run Kotlin library tests'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bazelw test \
            --test_output=all \
            --build_tests_only \
            --config=remote-ci-debug \
            --config=remote-ci-macos \
            --config=remote-ci-macos-local-java8 \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //test/kotlin/io/envoyproxy/envoymobile:engine_builder_test \
            //test/kotlin/io/envoyproxy/envoymobile:pulse_client_impl_test
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
