name: android

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linuxdist:
    name: linux_dist
    runs-on: ubuntu-18.04
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/linux_ci_setup.sh
      - name: 'Build envoy.aar distributable'
        run: |
          export PATH=/usr/lib/llvm-8/bin:$PATH
          export CC=clang
          export CXX=clang++
          export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk-bundle
          bazel build --fat_apk_cpu=x86 //:android_dist
    # TODO: parallelize these two jobs
      - name: 'Build Java app'
        run: |
          export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk-bundle
          bazel build --fat_apk_cpu=x86 //examples/java/hello_world:hello_envoy
      - name: 'Build kotlin app'
        run: |
          export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk-bundle
          bazel build --fat_apk_cpu=x86 //examples/kotlin/hello_world:hello_envoy_kt
  macjava:
    name: mac_java_helloworld
    runs-on: macOS-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - uses: actions/download-artifact@v1
        with:
          name: envoy.aar
          path: dist/
      - run: ls -lh dist/
      - name: start simulator
        run: ./ci/mac_start_emulator.sh
      - run: ./bzldev mobile-install --fat_apk_cpu=x86 //examples/java/hello_world:hello_envoy
        name: 'Start java app'
      - run: 'adb logcat -e "successful response" -m 1'
        name: 'Check liveliness'
  mackotlin:
    name: mac_kotlin_helloworld
    runs-on: macOS-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - uses: actions/download-artifact@v1
        with:
          name: envoy.aar
          path: dist/
      - run: ls -lh dist/
      - name: start simulator
        run: ./ci/mac_start_emulator.sh
      - run: ./bzldev mobile-install --fat_apk_cpu=x86 //examples/kotlin/hello_world:hello_envoy_kt
        name: 'Start kotlin app'
      - run: 'adb logcat -e "successful response" -m 1'
        name: 'Check liveliness'
  kotlintests:
    name: kotlin_tests
    runs-on: ubuntu-18.04
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/linux_ci_setup.sh
      - run: bazel test --test_output=all --build_tests_only //library/kotlin/test/...
        name: 'Run Kotlin library tests'
  javatests:
    name: java_tests
    runs-on: ubuntu-18.04
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/linux_ci_setup.sh
      - run: bazel test --test_output=all --build_tests_only //library/java/test/...
        name: 'Run Java library tests'
