name: artifacts

on:
  push:
    branches:
      - main
    paths:
      - VERSION

jobs:
  main_android_dist_ci:
    name: main_android_dist_ci
    runs-on: macOS-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - name: 'Build envoy.aar distributable'
        run: |
          current_short_commit=$(git rev-parse --short HEAD)
          bazelisk build \
              --config=release-android \
              --fat_apk_cpu=x86,armeabi-v7a,arm64-v8a \
              --define=pom_version=main-$current_short_commit \
              //:android_dist_ci
      - uses: actions/upload-artifact@v2
        with:
          name: envoy_android_aar_sources
          path: bazel-bin/envoy_mobile.zip
  main_ios_dist:
    name: main_ios_dist
    runs-on: macOS-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - name: 'Build Envoy.framework distributable'
        run: bazelisk build --config=release-ios --ios_multi_cpus=i386,x86_64,armv7,arm64 //:ios_dist
      - name: 'Create temporary directory for artifact to produce properly named zip'
        run: mkdir -p dist/ios_artifact/Envoy.framework
      - name: 'Move artifact to directory for zipping'
        run: mv dist/Envoy.framework/* dist/ios_artifact/Envoy.framework
      - uses: actions/upload-artifact@v2
        with:
          name: envoy_ios_framework
          path: dist/ios_artifact
  main_ios_cocoapods:
    name: main_ios_cocoapods
    runs-on: macOS-latest
    timeout-minutes: 45
    needs: [main_ios_dist]
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - uses: actions/download-artifact@v2
        with:
          name: envoy_ios_framework
          path: dist/envoy_ios_cocoapods
      - name: 'Copy license for CocoaPods'
        run: cp LICENSE dist/envoy_ios_cocoapods
      - name: 'Create empty Swift sources directory'
        run: mkdir -p dist/envoy_ios_cocoapods/Envoy.framework/Swift
      - name: 'Create empty Swift file to force Swift libraries to link properly'
        run: touch dist/envoy_ios_cocoapods/Envoy.framework/Swift/Empty.swift
      - uses: actions/upload-artifact@v2
        with:
          name: envoy_ios_cocoapods
          path: dist/envoy_ios_cocoapods
