name: artifacts

on:
  pull_request:

jobs:
  master_ios_dist:
    name: master_ios_dist
    runs-on: macOS-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - name: 'Build Envoy.framework distributable'
        run: bazel build --config=release-ios --ios_multi_cpus=i386,x86_64,armv7,arm64 //:ios_dist
      - name: 'Create temporary directory for artifact to produce properly named zip'
        run: mkdir -p dist/ios_artifact/Envoy.framework
      - name: 'Move artifact to directory for zipping'
        run: mv dist/Envoy.framework/* dist/ios_artifact/Envoy.framework
      - uses: actions/upload-artifact@v1
        with:
          name: envoy_ios_framework
          path: dist/ios_artifact
  master_ios_cocoapods:
    name: master_ios_cocoapods
    runs-on: macOS-latest
    timeout-minutes: 45
    needs: [master_ios_dist]
    steps:
      - uses: actions/checkout@v1
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - name: 'Create temporary directory for artifact to produce properly named zip'
        run: mkdir -p dist/envoy_ios_cocoapods
      - uses: actions/download-artifact@v1
        with:
          name: envoy_ios_framework
          path: dist/envoy_ios_cocoapods/envoy_ios_cocoapods
      - name: 'Copy license for CocoaPods'
        run: cp LICENSE dist/envoy_ios_cocoapods/envoy_ios_cocoapods
      - name: 'Create empty Swift sources directory'
        run: mkdir -p dist/envoy_ios_cocoapods/envoy_ios_cocoapods/Envoy.framework/Swift
      - name: 'Create empty Swift file to force Swift libraries to link properly'
        run: touch dist/envoy_ios_cocoapods/envoy_ios_cocoapods/Envoy.framework/Swift/Empty.swift
      - uses: actions/upload-artifact@v1
        with:
          name: envoy_ios_cocoapods
          path: dist/envoy_ios_cocoapods
