name: artifacts

on: [push]

jobs:
  master_android_dist:
    name: master_android_dist
    runs-on: ubuntu-18.04
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/linux_ci_setup.sh
      - name: 'Build envoy.aar distributable'
        run: |
          touch dist/abc.txt
      - name: 'ls dist'
        run: |
          ls dist