name: artifacts

on: [push]

jobs:
  master_ios_dist:
    name: master_ios_dist
    runs-on: macOS-10.14
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - name: 'Build Envoy.framework distributable'
        run: ./bazelw build --config=ios --ios_multi_cpus=i386 //:ios_dist
      - name: 'Create temporary directory for artifact'
        run: mkdir -p dist/ios_artifact/Envoy.framework
      - name: 'Move artifact to directory to produce properly named zip'
        run: mv dist/Envoy.framework/* dist/ios_artifact/Envoy.framework
      - uses: actions/upload-artifact@v1
        with:
          name: envoy_ios_framework
          path: dist/ios_artifact
