name: artifacts

on:
  push:
    branches:
      - master

jobs:
  master_android_dist:
    name: master_android_dist
    runs-on: ubuntu-18.04
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/linux_ci_setup.sh
      - name: 'Build envoy.aar distributable'
        run: |
          export PATH=/usr/lib/llvm-8/bin:$PATH
          export CC=clang
          export CXX=clang++
          export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk-bundle
          current_short_commit=$(git rev-parse --short HEAD)
          bazel build \
              --config=release-android \
              --fat_apk_cpu=x86,armeabi-v7a,arm64-v8a \
              --define=pom_version=master-$current_short_commit \
              //:android_deploy
      - uses: actions/upload-artifact@v1
        with:
          name: envoy_android_aar_sources
          path: dist/envoy_aar_sources.zip
  master_ios_dist:
    name: master_ios_dist
    runs-on: macOS-10.14
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - name: 'Build Envoy.framework distributable'
        run: bazel build --config=release-ios --ios_multi_cpus=i386,x86_64,armv7,arm64 //:ios_dist
      - name: 'Create temporary directory for artifact to produce properly named zip'
        run: mkdir -p dist/ios_artifact/Envoy.framework
      - name: 'Move artifact to directory for zipping'
        run: mv dist/Envoy.framework/* dist/ios_artifact/Envoy.framework
      - uses: actions/upload-artifact@v1
        with:
          name: envoy_ios_framework
          path: dist/ios_artifact
  master_ios_cocoapods:
    name: master_ios_cocoapods
    runs-on: macOS-10.14
    timeout-minutes: 45
    needs: [master_ios_dist]
    steps:
      - uses: actions/checkout@v1
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - uses: actions/download-artifact@v1
        with:
          name: envoy_ios_framework
          path: dist/envoy_ios_cocoapods
      - name: 'Copy license for CocoaPods'
        run: cp LICENSE dist/envoy_ios_cocoapods
      - name: 'Create empty Swift sources directory'
        run: mkdir -p dist/envoy_ios_cocoapods/Envoy.framework/Swift
      - name: 'Create empty Swift file to force Swift libraries to link properly'
        run: touch dist/envoy_ios_cocoapods/Envoy.framework/Swift/Empty.swift
      - uses: actions/upload-artifact@v1
        with:
          name: envoy_ios_cocoapods
          path: dist/envoy_ios_cocoapods
