name: artifacts

on: [push]

jobs:
  master_android_dist:
    name: master_android_dist
    runs-on: ubuntu-18.04
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/linux_ci_setup.sh
      - name: 'Build envoy.aar distributable'
        run: |
          export PATH=/usr/lib/llvm-8/bin:$PATH
          export CC=clang
          export CXX=clang++
          export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk-bundle
          current_short_commit=$(git rev-parse --short HEAD)
          bazel build \
              --config=release-android \
              --fat_apk_cpu=x86,armeabi-v7a,arm64-v8a \
              --define=pom_version=master-$current_short_commit \
              //:android_deploy
      - uses: actions/upload-artifact@v1
        with:
          name: envoy_android_aar_sources
          path: dist/envoy_aar_sources.zip
