name: asan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  asan:
    name: asan
    runs-on: ubuntu-18.04
    timeout-minutes: 180
    container:
      image: envoyproxy/envoy-build-ubuntu:e33c93e6d79804bf95ff80426d10bdcc9096c785
      env:
        CC: /opt/llvm/bin/clang
        CXX: /opt/llvm/bin/clang++
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Run tests'
        run: bazel test --config=clang-asan --test_output=all --test_env=ENVOY_IP_TEST_VERSIONS=v4only //test/common/...
