name: bump_support_rotation

on:
  workflow_dispatch:
  schedule:
    # Mondays at 2pm UTC (9am EST)
    - cron: "0 14 * * 1"

jobs:
  bump_support_rotation:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'envoyproxy'
    permissions:
      pull-requests: write
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: Bump Lyft Support Rotation
        id: bump
        run: ./tools/bump_lyft_support_rotation.sh
      - name: Create PR
        id: pr
        uses: peter-evans/create-pull-request@923ad837f191474af6b1721408744feb989a4c27
        with:
          token: ${{ secrets.CREDENTIALS_GITHUB_PUSH_TOKEN }}
          title: Bump Lyft Support Rotation
          commit-message: |
            Bump Lyft Support Rotation

            Signed-off-by: GitHub Action <noreply@github.com>
          committer: GitHub Action <noreply@github.com>
          base: main
          delete-branch: true
          branch: support-bump
          branch-suffix: short-commit-hash
          reviewers: ${{ steps.bump.outputs.NEXT_MAINTAINER }}
      - name: Post to Slack
        run: |
          ./tools/post_to_slack.sh \
            "Lyft support maintainer changing from <https://github.com/${{ steps.bump.outputs.PREVIOUS_MAINTAINER }}|${{ steps.bump.outputs.PREVIOUS_MAINTAINER }}> to <https://github.com/${{ steps.bump.outputs.NEXT_MAINTAINER }}|${{ steps.bump.outputs.NEXT_MAINTAINER }}>: ${{ steps.pr.outputs.pull-request-url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
