name: commands
on:
  issue_comment:
    types: [created]

jobs:
  retest:
    name: Retest
    runs-on: ubuntu-latest
    steps:
      #       jpsim/retest@v1
      - uses: jpsim/retest@c158dec0a7f67cb85f8367468dc8a9a75308bb7f
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
