name: coverage

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'library/common/**'
      - 'test/**'

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/linux_ci_setup.sh
      - name: 'Run coverage'
        run: |
          export PATH=/usr/lib/llvm-8/bin:$PATH
          export CC=clang
          export CXX=clang++
          ./envoy/test/run_envoy_bazel_coverage.sh //test/...
          cat bazel-out/k8-fastbuild/testlogs/test/common/envoy_mobile_main_common_test/test.log
