name: coverage

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-18.04
    timeout-minutes: 45
    container:
      image: envoyproxy/envoy-build-ubuntu:5a096881181dbe478f642b7ac02a68e9591e933d
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Run coverage'
        run: ./test/coverage/run_coverage.sh
