name: coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-18.04
    timeout-minutes: 120
    defaults:
      run:
        shell: bash
    container:
      image: envoyproxy/envoy-build-ubuntu:8ca107a75ee98b255aa59db2ab40fd0800a3ce99
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - id: check_context
        name: 'Check whether to run'
        run: |
          echo "Coverage will run."
          echo "::set-output name=run_coverage::true"
      - name: 'Run coverage'
        if: steps.check_context.outputs.run_coverage == 'true'
        continue-on-error: true
        run: |
          echo "build --remote_header=\"Authorization=Bearer ${{ secrets.GITHUB_TOKEN }}\"" > ~/.bazelrc
          BAZEL_BUILD_OPTIONS="--config=remote-ci-linux-coverage" \
            PATH=/opt/llvm/bin:${PATH} \
            COVERAGE_THRESHOLD=95 \
            ./envoy/test/run_envoy_bazel_coverage.sh //test/common/...
      - name: 'Package coverage'
        if: steps.check_context.outputs.run_coverage == 'true'
        run: |
          tar -czvf coverage.tar.gz generated/coverage
      - name: 'Upload report'
        if: steps.check_context.outputs.run_coverage == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: coverage.tar.gz
          path: coverage.tar.gz
