name: coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-18.04
    timeout-minutes: 120
    defaults:
      run:
        shell: bash
    container:
      image: envoyproxy/envoy-build-ubuntu:e33c93e6d79804bf95ff80426d10bdcc9096c785
      env:
        CC: /opt/llvm/bin/clang
        CXX: /opt/llvm/bin/clang++
        GCOV: /opt/llvm/bin/llvm-profdata
        BAZEL_LLVM_COV: /opt/llvm/bin/llvm-cov
        BAZEL_USE_LLVM_NATIVE_COVERAGE: "1"
        COVERAGE_THRESHOLD: 95
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - id: check_context
        name: 'Check whether to run'
        run: |
          if git rev-parse --abbrev-ref HEAD | grep -q ^main$ || git diff --name-only origin/main | grep -qe common/ -e ^.github/workflows/coverage.yml ; then
            echo "Coverage will run."
            echo "::set-output name=run_coverage::true"
          else
            echo "Skipping coverage."
            echo "::set-output name=run_coverage::false"
          fi
      - name: 'Run coverage'
        if: steps.check_context.outputs.run_coverage == 'true'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        continue-on-error: true
        run: |
          env
          echo "build --remote_header=\"Authorization=Bearer ${{ secrets.GITHUB_TOKEN }}\"" >> ~/.bazelrc
          BAZEL_BUILD_OPTIONS="--config=remote-ci-linux-coverage" \
            BAZEL_USE_LLVM_NATIVE_COVERAGE=1 \
            PATH=/opt/llvm/bin:${PATH} \
            ./envoy/test/run_envoy_bazel_coverage.sh //test/common/foo:a_test
      - name: 'Package coverage'
        if: steps.check_context.outputs.run_coverage == 'true'
        run: |
          env
          whereis gcov
          whereis llvm-cov
          whereis llvm-profdata
          cat $(find bazel-out/ -name "test.log")
          tar -czvf coverage.tar.gz generated/coverage
      - name: 'Upload report'
        if: steps.check_context.outputs.run_coverage == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: coverage.tar.gz
          path: coverage.tar.gz
