name: format

on: [push]

jobs:
  formatall:
    name: format_all
    runs-on: ubuntu-18.04
    timeout-minutes: 45
    container:
      image: envoyproxy/envoy-build-ubuntu@sha256:47380d6ec4a83599fc0fce8f6ef5ee216ecb06c643d195fa43ba6c71f878a9ea
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Run formatters'
        run: |
          # TODO: need to figure out why the container above does not have clang-format-9.
          export CLANG_FORMAT=clang-format-8
          export BUILDIFIER_BIN=/usr/local/bin/buildifier
          ./tools/check_format.sh
  precommit:
    name: precommit
    runs-on: macOS-10.14
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
      - name: 'Install precommit'
        run: brew install pre-commit
      - name: 'Run precommit'
        run: pre-commit run --all-files
  swiftlint:
    name: swift_lint
    runs-on: ubuntu-18.04
    timeout-minutes: 45
    container:
      image: norionomura/swiftlint:0.33.0_swift-5.0
    steps:
      - uses: actions/checkout@v1
      - name: 'Run SwiftLint'
        run: swiftlint lint --strict
  kotlinlint:
    name: kotlin_lint
    runs-on: ubuntu-18.04
    timeout-minutes: 45
    container:
      image: openjdk:8-jdk
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Run Kotlin lint'
        run: ./ci/kotlin_lint.sh
