name: ios

on: [push]

jobs:
  macdist:
    name: mac_dist
    runs-on: macOS-10.14
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - name: 'Build Envoy.framework distributable'
        run: ./bazelw build --config=ios //:ios_dist
      - name: 'Zip Envoy.framework.zip distributable'
        run: zip -r dist/Envoy.framework.zip dist/Envoy.framework
      - run: ls -lh dist/
      - uses: actions/upload-artifact@v1
        with:
          name: Envoy.framework.zip
          path: dist/Envoy.framework.zip
  macswift:
    name: mac_swift_helloworld
    needs: macdist
    runs-on: macOS-10.14
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - uses: actions/download-artifact@v1
        with:
          name: Envoy.framework.zip
          path: dist/
      - run: unzip dist/Envoy.framework.zip
      - run: ls -lh dist/
      - name: 'Build swift app'
        run: ./bazelw build --config=ios //examples/swift/hello_world:app
      # Run the app in the background and redirect logs.
      - name: 'Run swift app'
        run: ./bazelw run --config=ios //examples/swift/hello_world:app &> /tmp/envoy.log &
      # Wait for the app to start and get some requests/responses.
      - name: 'Sleep'
        run: sleep 120
      # Check for the sentinel value that shows the app is alive and well.
      - name: 'Check liveliness'
        run: 'cat /tmp/envoy.log'
  macobjc:
    name: mac_objc_helloworld
    needs: macdist
    runs-on: macOS-10.14
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - uses: actions/download-artifact@v1
        with:
          name: Envoy.framework.zip
          path: dist/
      - run: unzip dist/Envoy.framework.zip
      - run: ls -lh dist/
      - name: 'Build objective-c app'
        run: ./bazelw build --config=ios //examples/objective-c/hello_world:app
      # Run the app in the background and redirect logs.
      - name: 'Run objective-c app'
        run: ./bazelw run --config=ios //examples/objective-c/hello_world:app &> /tmp/envoy.log &
      # Wait for the app to start and get some requests/responses.
      - name: 'Sleep'
        run: sleep 120
      # Check for the sentinel value that shows the app is alive and well.
      - name: 'Check liveliness'
        run: 'cat /tmp/envoy.log'
  swifttests:
    name: swift_tests
    runs-on: macOS-10.14
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
  # TODO: Fix and re-enable swift unit tests:
  # https://github.com/lyft/envoy-mobile/issues/383
  #     - name: 'Install dependencies'
  #       run: ./ci/mac_ci_setup.sh
  #     - name: 'Run swift library tests'
  #       run: ./bazelw test --test_output=all --config=ios --build_tests_only //library/swift/test/...
