name: ios

on: [push]

jobs:
  # macdist:
  #   name: mac_dist
  #   runs-on: macOS-10.14
  #   timeout-minutes: 45
  #   steps:
  #     - uses: actions/checkout@v1
  #       with:
  #         submodules: true
  #     - name: 'Install dependencies'
  #       run: ./ci/mac_ci_setup.sh
  #     - name: 'Build Envoy.framework distributable'
  #       run: ./bazelw build --config=ios //:ios_dist
  #     - name: 'Zip Envoy.framework.zip distributable'
  #       run: zip -r dist/Envoy.framework.zip dist/Envoy.framework
  #     - run: ls -lh dist/
  #     - uses: actions/upload-artifact@v1
  #       with:
  #         name: Envoy.framework.zip
  #         path: dist/Envoy.framework.zip
  # macswift:
  #   name: mac_swift_helloworld
  #   needs: macdist
  #   runs-on: macOS-10.14
  #   timeout-minutes: 45
  #   steps:
  #     - uses: actions/checkout@v1
  #       with:
  #         submodules: true
  #     - name: 'Install dependencies'
  #       run: ./ci/mac_ci_setup.sh
  #     - uses: actions/download-artifact@v1
  #       with:
  #         name: Envoy.framework.zip
  #         path: dist/
  #     - run: unzip dist/Envoy.framework.zip
  #     - run: ls -lh dist/
  #     - name: 'Build swift app'
  #       run: ./bazelw build --config=ios //examples/swift/hello_world:app
  #     # TODO: re-enable liveliness test.
  #     # - run: npm install -g ios-sim && ios-sim start --devicetypeid "iPhone-X, 12.2"
  #     #   name: 'Start the iOS simulator'
  #     # # Run the app in the background and redirect logs.
  #     # - run: ./bazelw run --config=ios //examples/swift/hello_world:app &> /tmp/envoy.log &
  #     #   name: 'Run swift app'
  #     # # Wait for the app to start and get some requests/responses.
  #     # - run: sleep 60
  #     #   name: 'Sleep'
  #     # # Check for the sentinel value that shows the app is alive and well.
  #     # - run: cat /tmp/envoy.log | grep 'Hello, world!'
  #     #   name: 'Check liveliness'
  # macobjc:
  #   name: mac_objc_helloworld
  #   needs: macdist
  #   runs-on: macOS-10.14
  #   timeout-minutes: 45
  #   steps:
  #     - uses: actions/checkout@v1
  #       with:
  #         submodules: true
  #     - name: 'Install dependencies'
  #       run: ./ci/mac_ci_setup.sh
  #     - uses: actions/download-artifact@v1
  #       with:
  #         name: Envoy.framework.zip
  #         path: dist/
  #     - run: unzip dist/Envoy.framework.zip
  #     - run: ls -lh dist/
  #     - name: 'Build objective-c app'
  #       run: ./bazelw build --config=ios //examples/objective-c/hello_world:app
      # TODO: re-enable liveliness test (same as swift).
  swifttests:
    name: swift_tests
    runs-on: macOS-10.14
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      # TODO: Remove xcode_version and ios_simulator_version overrides and use .bazelrc.
      # CI machines are unable to start tests on 10.3.0, likely due to the fact
      # that multiple versions of Xcode are installed:
      # '(domain=com.apple.CoreSimulator.SimError, code=165): Invalid device state'
      - name: 'Run swift library tests'
        run: ./bazelw test --xcode_version=10.2.1 --ios_simulator_version=12.2 --test_output=all --config=ios --build_tests_only //library/swift/test/...
