name: ios

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  macdist:
    name: mac_dist
    runs-on: macOS-latest
    timeout-minutes: 75
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - name: 'Build Envoy.framework distributable'
        run: bazelisk build --config=ios //:ios_dist
      - name: 'Zip Envoy.framework.zip distributable'
        run: zip -r dist/Envoy.framework.zip dist/Envoy.framework
      - run: ls -lh dist/
      - uses: actions/upload-artifact@v2
        with:
          name: Envoy.framework.zip
          path: dist/Envoy.framework.zip
  macswift:
    name: mac_swift_helloworld
    needs: macdist
    runs-on: macOS-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - uses: actions/download-artifact@v2
        with:
          name: Envoy.framework.zip
          path: dist/
      - run: unzip dist/Envoy.framework.zip
      - run: ls -lh dist/
      - name: 'Build swift app'
        run: bazelisk build --config=ios //examples/swift/hello_world:app
      # Run the app in the background and redirect logs.
      - name: 'Run swift app'
        run: bazelisk run --config=ios //examples/swift/hello_world:app &> /tmp/envoy.log &
      - name: 'Check liveliness'
        run: sed '/received headers with status 200/q' <(touch /tmp/envoy.log && tail -F /tmp/envoy.log)
  macobjc:
    name: mac_objc_helloworld
    needs: macdist
    runs-on: macOS-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - uses: actions/download-artifact@v2
        with:
          name: Envoy.framework.zip
          path: dist/
      - run: unzip dist/Envoy.framework.zip
      - run: ls -lh dist/
      - name: 'Build objective-c app'
        run: bazelisk build --config=ios //examples/objective-c/hello_world:app
      # Run the app in the background and redirect logs.
      - name: 'Run objective-c app'
        run: bazelisk run --config=ios //examples/objective-c/hello_world:app &> /tmp/envoy.log &
      - name: 'Check liveliness'
        run: sed '/received headers with status 200/q' <(touch /tmp/envoy.log && tail -F /tmp/envoy.log)
  swifttests:
    name: swift_tests
    runs-on: macOS-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - name: 'Run swift library tests'
        run: bazelisk test --test_output=all --config=ios --build_tests_only //library/swift/test/...
