name: ios_tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  swifttests:
    name: swift_tests_new
    runs-on: macOS-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - name: 'Run swift library tests'
        run: bazelisk test --test_output=all --config=ios --build_tests_only //test/swift/...
