name: ios_apps

on:
  workflow_run:
    workflows: ["ios_build"]
    types: [completed]

jobs:
  swifthelloworld:
    name: swift_helloworld
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: macOS-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - uses: actions/download-artifact@v2
        with:
          name: Envoy.framework.zip
          path: dist/
      - run: unzip dist/Envoy.framework.zip
      - run: ls -lh dist/
      - name: 'Build swift app'
        run: bazelisk build --config=ios //examples/swift/hello_world:app
      # Run the app in the background and redirect logs.
      - name: 'Run swift app'
        run: bazelisk run --config=ios //examples/swift/hello_world:app &> /tmp/envoy.log &
      - name: 'Check connectivity'
        run: sed '/received headers with status 200/q' <(touch /tmp/envoy.log && tail -F /tmp/envoy.log)
      - name: Log app run
        if: ${{ failure() || cancelled() }}
        run: cat /tmp/envoy.log
  objchelloworld:
    name: objc_helloworld
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: macOS-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - uses: actions/download-artifact@v2
        with:
          name: Envoy.framework.zip
          path: dist/
      - run: unzip dist/Envoy.framework.zip
      - run: ls -lh dist/
      - name: 'Build objective-c app'
        run: bazelisk build --config=ios //examples/objective-c/hello_world:app
      # Run the app in the background and redirect logs.
      - name: 'Run objective-c app'
        run: bazelisk run --config=ios //examples/objective-c/hello_world:app &> /tmp/envoy.log &
      - name: 'Check connectivity'
        run: sed '/received headers with status 200/q' <(touch /tmp/envoy.log && tail -F /tmp/envoy.log)
      - name: Log app run
        if: ${{ failure() || cancelled() }}
        run: cat /tmp/envoy.log
