name: javadocstesting

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linuxdist:
    name: linux_dist
    runs-on: ubuntu-18.04
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/linux_ci_setup.sh
      # TODO: parallelize these two jobs
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - name: 'straight javadoc'
        run: |
          export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk-bundle
          bazel build --fat_apk_cpu=x86 //:javadocs
      - name: 'aar javadoc'
        run: |
          export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk-bundle
          bazel build --fat_apk_cpu=x86 //library/kotlin/src/io/envoyproxy/envoymobile:android_aar_android_javadocs
  macdist:
    name: mac_dist
    runs-on: macOS-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - run: ./ci/mac_ci_setup.sh
        name: 'Install dependencies'
      - name: 'straight javadoc'
        run: |
          export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk-bundle
          bazel build --fat_apk_cpu=x86 //:javadocs
      - name: 'aar javadoc'
        run: |
          export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk-bundle
          bazel build --fat_apk_cpu=x86 //library/kotlin/src/io/envoyproxy/envoymobile:android_aar_android_javadocs