name: python_tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pythontests:
    name: python_tests
    runs-on: ubuntu-18.04
    timeout-minutes: 90
    container:
      image: envoyproxy/envoy-build-ubuntu@sha256:8c1f2988318b29df9d70b32ca5a78cf5c95b5732524e71fd97e6eff8a1d0a1bd
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Add safe directory
        run: git config --global --add safe.directory /__w/envoy-mobile/envoy-mobile
      - id: check_context
        name: 'Check whether to run'
        run: |
          if git rev-parse --abbrev-ref HEAD | grep -q ^main$ || git diff --name-only origin/main | grep -qe common/ -e cc/ -e python/ -e bazel/ -e ^\.bazelrc$ -e ^envoy$ -e ^WORKSPACE$ -e ^.github/workflows/python_tests.yml$ ; then
            echo "Tests will run."
            echo "::set-output name=run_tests::true"
          else
            echo "Skipping tests."
            echo "::set-output name=run_tests::false"
          fi
      - name: 'Run tests'
        if: steps.check_context.outputs.run_tests == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bazelw test \
            --action_env=LD_LIBRARY_PATH \
            --test_output=all \
            --config=remote-ci-linux \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //test/python/...
