name: release_validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cocoapods_spec_lint:
    name: cocoapods_spec_lint
    runs-on: macos-12
    timeout-minutes: 20
    if: ${{ false }} # TODO(jpsim): Fix this validation when bumping versions
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: 'Lint CocoaPods podspec'
        run: bundle exec pod spec lint
