name: release

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  android_aar_sonatype_deploy:
    name: android_deploy
    runs-on: ubuntu-18.04
    timeout-minutes: 240
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/linux_ci_setup.sh
      - name: 'Configure envoy-bot git user'
        run: |
          # Switch global user to be envoy-bot for deployment
          git config --global user.email "envoy-bot@users.noreply.github.com"
          git config --global user.name "envoy-bot"
      - name: 'Build envoy.aar distributable'
        run: |
          export PATH=/usr/lib/llvm-8/bin:$PATH
          export CC=clang
          export CXX=clang++
          export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk-bundle

          # Build and create the artifacts
          bazelisk build \
            --config=release-android \
            --fat_apk_cpu=x86,armeabi-v7a,arm64-v8a \
            --define=pom_version="1" \
            //:android_dist_ci
