name: submodule_update

on:
  workflow_dispatch:
  schedule:
    # Mondays at 2pm UTC (9am EST)
    - cron: "0 14 * * 1"

jobs:
  submodule_update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Fetch latest submodule
      run: |
        git submodule update --remote
    - name: Check for changes
      id: state
      run: |
        if ! git diff-index --quiet HEAD --; then
          echo "Detected changes..."
          echo "::set-output name=dirty::true"
        fi
    - name: Get current support maintainer
      if: steps.state.outputs.dirty == 'true'
      id: support
      run: |
        maintainers_file=".github/lyft_maintainers.yml"
        first_line="$(head -n 1 "$maintainers_file")"
        current=${first_line#"current: "}
        echo "::set-output name=maintainer::$current"
    - name: Create PR
      if: steps.state.outputs.dirty == 'true'
      uses: peter-evans/create-pull-request@923ad837f191474af6b1721408744feb989a4c27
      with:
        token: ${{ secrets.CREDENTIALS_GITHUB_PUSH_TOKEN }}
        title: Update Envoy
        commit-message: |
            Update Envoy

            Signed-off-by: GitHub Action <noreply@github.com>
        committer: GitHub Action <noreply@github.com>
        base: main
        delete-branch: true
        branch: update-envoy
        branch-suffix: timestamp
        reviewers: ${{ steps.support.outputs.maintainer }}
