name: weekly_release

on:
  workflow_dispatch:
  schedule:
    # Mondays at 1pm UTC (8am EST)
    - cron: "0 13 * * 1"

jobs:
  weekly_release:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'envoyproxy'
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: 'Configure envoy-bot git user'
        run: |
          # Switch global user to be envoy-bot for deployment
          git config --global user.email "envoy-bot@users.noreply.github.com"
          git config --global user.name "envoy-bot"
      - name: Set version
        run: |
          echo "$(cat VERSION).$(date +'%Y%m%d')" > VERSION
          git add VERSION
          git commit -m "Release version $(cat VERSION)

          Signed-off-by: envoy-bot <envoy-bot@users.noreply.github.com>"
      - name: Create tag
        run: |
          version="v$(cat VERSION)"
          git tag -a ${version} -m ${version}
          git push origin ${version}
